name: Build Linux Release

on:
  push:
    branches: [ main, unstable, add-proxy-support ]
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.15.0'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3

    - name: Install yarn
      run: npm install -g yarn

    - name: Install project dependencies
      run: yarn install

    - name: Build
      run: yarn build-linux

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: session-desktop-linux
        path: dist/
